name: Show Squashed Merge Commit on PR Comment

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  contents: write
  issues: write

jobs:
  show-squash-commit:
    if: |
      github.event.issue.pull_request != null &&
      startsWith(github.event.comment.body, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            console.log({
              base: pr.data.base.ref,
              head: pr.data.head.ref,
              title: pr.data.title,
              body: pr.data.body
            });

            echo "base=${pr.data.base.ref}" >> $GITHUB_OUTPUT
            echo "head=${pr.data.head.ref}" >> $GITHUB_OUTPUT
            echo "title=${pr.data.title}" >> $GITHUB_OUTPUT
            echo "body=${pr.data.body}" >> $GITHUB_OUTPUT

            return {
              base: pr.data.base.ref,
              head: pr.data.head.ref,
              title: pr.data.title,
              body: pr.data.body
            };

      - name: Create squash merge commit
        id: squash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "=== PR Object Output ==="
          echo "base: ${{ steps.pr.outputs.base }}"
          echo "head: ${{ steps.pr.outputs.head }}"
          echo "title: ${{ steps.pr.outputs.title }}"
          echo "body: ${{ steps.pr.outputs.body }}"
          echo "========================"

          git fetch --unshallow origin main
          git checkout ${{ steps.pr.outputs.base }}
          git merge --squash ${{ steps.pr.outputs.head }}
          git commit -m "${{ steps.pr.outputs.title }}" -m "${{ steps.pr.outputs.body }}"
          echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "Squashed commit hash: $(git rev-parse HEAD)"

      - name: Show squashed commit
        run: |
          git show ${{ steps.squash.outputs.commit_sha }}
