name: Show Squashed Merge Commit on PR Comment

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  contents: write
  issues: write

jobs:
  show-squash-commit:
    if: |
      github.event.issue.pull_request != null &&
      startsWith(github.event.comment.body, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            return JSON.stringify({
              base: pr.data.base.ref,
              head: pr.data.head.ref,
              title: pr.data.title,
              body: pr.data.body
            })

      - name: Create squash merge commit
        id: squash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          pr_info='${{ steps.pr.outputs.result }}'

          echo "PR INFO: $pr_info"

          base=$(echo "$pr_info" | jq -r '.base')
          head=$(echo "$pr_info" | jq -r '.head')
          title=$(echo "$pr_info" | jq -r '.title')
          body=$(echo "$pr_info" | jq -r '.body')

          echo "base: $base"
          echo "head: $head"
          echo "title: $title"
          echo "body: $body"

          git fetch --unshallow origin main
          git checkout $base


      - name: Show squashed commit
        run: |
          git show ${{ steps.squash.outputs.commit_sha }}
